namespace Laser_JCZ
{
	public enum LmcErrCode
	{
		LMC1_ERR_SUCCESS = 0,
		LMC1_ERR_EZCADRUN = 1,
		LMC1_ERR_NOFINDCFGFILE = 2,
		LMC1_ERR_FAILEDOPEN = 3,
		LMC1_ERR_NODEVICE = 4,
		LMC1_ERR_HARDVER = 5,
		LMC1_ERR_DEVCFG = 6,
		LMC1_ERR_STOPSIGNAL = 7,
		LMC1_ERR_USERSTOP = 8,
		LMC1_ERR_UNKNOW = 9,
		LMC1_ERR_OUTTIME = 10,
		LMC1_ERR_NOINITIAL = 11,
		LMC1_ERR_READFILE = 12,
		LMC1_ERR_OWENWNDNULL = 13,
		LMC1_ERR_NOFINDFONT = 14,
		LMC1_ERR_PENNO = 0xF,
		LMC1_ERR_NOTTEXT = 0x10,
		LMC1_ERR_SAVEFILE = 17,
		LMC1_ERR_NOFINDENT = 18,
		LMC1_ERR_STATUE = 19,
		LMC1_ERR_PARAM = 20,
		LMC1_ERR_BRAND = 21,
		LMC1_ERROR_NOEZDFILE = 22,
		LMC1_ERROR_NOINIT = 23,
		LMC1_ERROR_OUTOFPORTRANGE = 24,
		LMC1_ERROR_NOFINDMARKEZD = 25,
		LMC1_ERROR_NOUSBDOG = 80
	}
}
